# Generated by Django 5.1.2 on 2024-10-28 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='is_recurring',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('mips', 'MIPS'), ('internet_banking', 'Internet Banking'), ('juice_mcb', 'Juice MCB'), ('standing_order', 'Standing Order')], max_length=20),
        ),
    ]
