# Generated by Django 5.1.2 on 2024-10-28 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0002_subscription_is_recurring_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('mips', 'MIPS'), ('internet_banking', 'Internet Banking'), ('juice_mcb', 'Juice MCB'), ('standing_order', 'Standing Order'), ('paypal', 'PayPal')], default='paypal', max_length=20),
        ),
    ]
